Repository thoth-station/solver-errors-reporter, pull requests merged in 2020-09, with the labels that each got.

#18 Use thoth-report-processing and introduce new methods
  Pipfile
  Pipfile.lock
  notebooks/ClusterErrors.ipynb
  notebooks/PreprocessSolverErrorData.ipynb
Labels: approved, size/XXL

#19 Automatic update of dependency thoth-storages from 0.25.5 to 0.25.10
  Pipfile.lock
Labels: approved, bot

#20 Automatic update of dependency thoth-report-processing from 0.3.3 to 0.3.4
  Pipfile.lock
Labels: approved, bot, size/L
