Repository thoth-station/solver-errors-reporter, pull requests merged in 2020-08, with the labels that each got.

#5 Added Preprocessing and Clustering notebooks
  Pipfile
  Pipfile.lock
  README.md
  models/word2vec.model
  notebooks/ClusterErrors.ipynb
  notebooks/PreprocessSolverErrorData.ipynb
  template/__init__.py
  version.py
Labels: approved, size/XXL

#9 Release of version 0.1.1
  CHANGELOG.md
  version.py
Labels: approved, bot, size/XS

#10 Automatic update of dependency kneed from 0.6.0 to 0.7.0
  Pipfile.lock
Labels: approved, bot, size/L

#11 Added parameters for papermill
  .env.template
  Pipfile
  Pipfile.lock
  README.md
  models/word2vec.model
  notebooks/ClusterErrors.ipynb
  notebooks/PreprocessSolverErrorData.ipynb
Labels: approved, size/XXL

#13 Fixed Dependency Management Error
  Pipfile.lock
Labels: approved, size/L

#16 Fixed pipenv dependency issue.
  Pipfile
  Pipfile.lock
Labels: approved, size/M
